Thu Jan 19 18:11:52 GMT-03:00 2012 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOFeriado.<init>(DAOFeriado.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:62)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.Main.loadPreferences(Main.java:54)
	at senai.cronos.Main.init(Main.java:39)
	at senai.cronos.Main.main(Main.java:22)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 22 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOFeriado.<init>(DAOFeriado.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:62)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.Main.loadPreferences(Main.java:54)
	at senai.cronos.Main.init(Main.java:39)
	at senai.cronos.Main.main(Main.java:22)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:57 GMT-03:00 2012 Thread[Thread-4,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.horarios.HorariosGerarPanel$6.run(HorariosGerarPanel.java:205)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.horarios.HorariosGerarPanel$6.run(HorariosGerarPanel.java:205)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:57 GMT-03:00 2012 Thread[Thread-5,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.horarios.HorariosExibirPanel$5.run(HorariosExibirPanel.java:186)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.horarios.HorariosExibirPanel$5.run(HorariosExibirPanel.java:186)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:57 GMT-03:00 2012 Thread[Thread-7,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAODocente.<init>(DAODocente.java:28)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:44)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DocenteUI$2.run(DocenteUI.java:88)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAODocente.<init>(DAODocente.java:28)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:44)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DocenteUI$2.run(DocenteUI.java:88)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:57 GMT-03:00 2012 Thread[Thread-6,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DocenteUI$1.run(DocenteUI.java:61)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DocenteUI$1.run(DocenteUI.java:61)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-8,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDocente$1.run(CadastroDocente.java:81)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDocente$1.run(CadastroDocente.java:81)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-9,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAODocente.<init>(DAODocente.java:28)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:44)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDocente$4.run(CadastroDocente.java:223)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAODocente.<init>(DAODocente.java:28)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:44)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDocente$4.run(CadastroDocente.java:223)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-11,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOUnidadeCurricular.<init>(DAOUnidadeCurricular.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:59)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDisciplinas$2.run(CadastroDisciplinas.java:111)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOUnidadeCurricular.<init>(DAOUnidadeCurricular.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:59)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDisciplinas$2.run(CadastroDisciplinas.java:111)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-10,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDisciplinas$1.run(CadastroDisciplinas.java:72)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroDisciplinas$1.run(CadastroDisciplinas.java:72)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-12,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroTurmas$1.run(CadastroTurmas.java:62)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroTurmas$1.run(CadastroTurmas.java:62)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-14,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOLaboratorio.<init>(DAOLaboratorio.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:50)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroLaboratorios$3.run(CadastroLaboratorios.java:108)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOLaboratorio.<init>(DAOLaboratorio.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:50)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroLaboratorios$3.run(CadastroLaboratorios.java:108)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:58 GMT-03:00 2012 Thread[Thread-13,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroTurmas$4.run(CadastroTurmas.java:170)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.cadastro.CadastroTurmas$4.run(CadastroTurmas.java:170)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:59 GMT-03:00 2012 Thread[Thread-15,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.TurmaUI$1.run(TurmaUI.java:69)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOTurma.<init>(DAOTurma.java:20)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:56)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.TurmaUI$1.run(TurmaUI.java:69)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:59 GMT-03:00 2012 Thread[Thread-17,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOUnidadeCurricular.<init>(DAOUnidadeCurricular.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:59)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DisciplinaUI$2.run(DisciplinaUI.java:86)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAOUnidadeCurricular.<init>(DAOUnidadeCurricular.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:59)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DisciplinaUI$2.run(DisciplinaUI.java:86)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jan 19 18:11:59 GMT-03:00 2012 Thread[Thread-16,6,main] Cleanup action starting
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DisciplinaUI$1.run(DisciplinaUI.java:61)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Database 'cronos' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:579)
	at java.sql.DriverManager.getConnection(DriverManager.java:221)
	at senai.cronos.database.ConnectionFactory.getConnection(ConnectionFactory.java:31)
	at senai.cronos.database.Database.conexao(Database.java:25)
	at senai.cronos.database.dao.DAONucleo.<init>(DAONucleo.java:19)
	at senai.cronos.database.DAOFactory.getDao(DAOFactory.java:53)
	at senai.cronos.Fachada.get(Fachada.java:76)
	at senai.cronos.gui.DisciplinaUI$1.run(DisciplinaUI.java:61)
	at java.lang.Thread.run(Thread.java:722)
============= end nested exception, level (1) ===========
Cleanup action completed
